services:
  - type: web
    name: mern-task-manager-backend
    env: node
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free

services:
  - type: web
    name: mern-task-manager-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: https://task-manager-ua0c.onrender.com/api
